ingress:
  enabled: true
  paths:
    - /*
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

modules:
  text2vec-openai:
    enabled: true
    apiKey: 'MODULES_API_KEY'
  generative-openai:
    enabled: true
    apiKey: 'MODULES_API_KEY'
